title: Event

tabs:
  content:
    label: Content
    icon: text
    columns:
      left:
        width: 2/3
        sections:
          hero:
            label: Hero Section
            type: fields
            fields:
              header:
                label: Title
                type: text
              postfix:
                label: Postfix
                type: text
              featured_image:
                label: Featured Image
                type: files
                multiple: false

          about:
            label: About Section
            type: fields
            fields:
              introduction:
                label: Introduction
                type: writer
              about_image:
                label: Image
                type: files
                multiple: false

          schedule:
            label: Schedule Section
            type: fields
            fields:
              blocks:
                label: Blocks
                type: blocks
                fieldsets:
                  - eventblock
                  - scheduleblock

      right:
        width: 1/3
        sections:
          details:
            label: Event Details
            type: fields
            fields:
              time:
                label: Time
                type: text
              location:
                label: Location
                type: text
              cost:
                label: Cost
                type: text
              description:
                label: Description
                type: textarea

  seo:
    extends: tabs/seo